class DelPrimer3Fields < ActiveRecord::Migration
  def change
     remove_column :primer3s, :primer_error
          remove_column :primer3s, :primer_warning
              remove_column :primer3s, :primer_left_num_returned
                  remove_column :primer3s, :primer_right_num_returned
                      remove_column :primer3s, :primer_internal_num_returned
                          remove_column :primer3s, :primer_pair_num_returned
                              remove_column :primer3s, :primer_left_4_problems
                                  remove_column :primer3s, :primer_internal_4_problems
                                      remove_column :primer3s, :primer_right_4_problems
                                          remove_column :primer3s, :primer_left_explain
                                              remove_column :primer3s, :primer_internal_explain
                                                  remove_column :primer3s, :primer_right_explain
                                                      remove_column :primer3s, :primer_pair_explain
                                                          remove_column :primer3s, :primer_left_4
                                                              remove_column :primer3s, :primer_internal_4
                                                                  remove_column :primer3s, :primer_right_4
                                                                      remove_column :primer3s, :primer_left_4_sequence
                                                                          remove_column :primer3s, :primer_internal_4_sequence
                                                                              remove_column :primer3s, :primer_right_4_sequence
                                                                                  remove_column :primer3s, :primer_pair_4_product_size
                                                                                      remove_column :primer3s, :primer_left_4_penalty
                                                                                          remove_column :primer3s, :primer_internal_4_penalty
                                                                                              remove_column :primer3s, :primer_right_4_penalty
                                                                                                  remove_column :primer3s, :primer_pair_4_penalty
                                                                                                      remove_column :primer3s, :primer_left_4_tm
                                                                                                          remove_column :primer3s, :primer_internal_4_tm
                                                                                                              remove_column :primer3s, :primer_right_4_tm
                                                                                                                  remove_column :primer3s, :primer_pair_4_product_tm
                                                                                                                      remove_column :primer3s, :primer_pair_4_product_tm_oligo_tm_diff
                                                                                                                          remove_column :primer3s, :primer_pair_4_t_opt_a
                                                                                                                              remove_column :primer3s, :primer_left_4_gc_percent
                                                                                                                                  remove_column :primer3s, :primer_internal_4_gc_percent
                                                                                                                                      remove_column :primer3s, :primer_right_4_gc_percent
                                                                                                                                          remove_column :primer3s, :primer_left_4_self_any
                                                                                                                                              remove_column :primer3s, :primer_internal_4_self_any
                                                                                                                                                  remove_column :primer3s, :primer_right_4_self_any
                                                                                                                                                      remove_column :primer3s, :primer_left_4_self_any_th
                                                                                                                                                          remove_column :primer3s, :primer_internal_4_self_any_th
                                                                                                                                                              remove_column :primer3s, :primer_right_4_self_any_th
                                                                                                                                                                  remove_column :primer3s, :primer_right_4_hairpin_th
                                                                                                                                                                      remove_column :primer3s, :primer_pair_4_compl_any
                                                                                                                                                                          remove_column :primer3s, :primer_pair_4_compl_any_th
                                                                                                                                                                              remove_column :primer3s, :primer_left_4_self_end
                                                                                                                                                                                  remove_column :primer3s, :primer_internal_4_self_end
                                                                                                                                                                                      remove_column :primer3s, :primer_right_4_self_end
                                                                                                                                                                                          remove_column :primer3s, :primer_left_4_self_end_th
                                                                                                                                                                                              remove_column :primer3s, :primer_internal_4_self_end_th
                                                                                                                                                                                                  remove_column :primer3s, :primer_right_4_self_end_th
                                                                                                                                                                                                      remove_column :primer3s, :primer_left_4_hairpin_th
                                                                                                                                                                                                          remove_column :primer3s, :primer_internal_4_hairpin_th
                                                                                                                                                                                                              remove_column :primer3s, :primer_pair_4_compl_end
                                                                                                                                                                                                                  remove_column :primer3s, :primer_pair_4_compl_end_th
                                                                                                                                                                                                                      remove_column :primer3s, :primer_left_4_end_stability
                                                                                                                                                                                                                          remove_column :primer3s, :primer_right_4_end_stability
                                                                                                                                                                                                                              remove_column :primer3s, :primer_left_4_template_mispriming
                                                                                                                                                                                                                                  remove_column :primer3s, :primer_right_4_template_mispriming
                                                                                                                                                                                                                                      remove_column :primer3s, :primer_pair_4_template_mispriming
                                                                                                                                                                                                                                          remove_column :primer3s, :primer_left_4_template_mispriming_th
                                                                                                                                                                                                                                              remove_column :primer3s, :primer_right_4_template_mispriming_th
                                                                                                                                                                                                                                                  remove_column :primer3s, :primer_pair_4_template_mispriming_th
                                                                                                                                                                                                                                                      remove_column :primer3s, :primer_left_4_library_mispriming
                                                                                                                                                                                                                                                          remove_column :primer3s, :primer_right_4_library_mispriming
                                                                                                                                                                                                                                                              remove_column :primer3s, :primer_pair_4_library_mispriming
                                                                                                                                                                                                                                                                  remove_column :primer3s, :primer_internal_4_library_mishyb
                                                                                                                                                                                                                                                                      remove_column :primer3s, :primer_left_4_min_seq_quality
                                                                                                                                                                                                                                                                          remove_column :primer3s, :primer_internal_4_min_seq_quality
                                                                                                                                                                                                                                                                              remove_column :primer3s, :primer_right_4_min_seq_quality
                                                                                                                                                                                                                                                                                  remove_column :primer3s, :primer_stop_codon_position
                                                                                                                                                                                                                                                                                      remove_column :primer3s, :primer_left_4_position_penalty
                                                                                                                                                                                                                                                                                          remove_column :primer3s, :primer_right_4_position_penalty
  end
end
