# Template class holding all Primer3 input fields
# No data stored in the database
# The standard Primer3 defaults are stored here
class Primer3Template < Primer3
  
  # TODO Both PRIMER_MIN_THREE_PRIME_DISTANCE and PRIMER_{LEFT/RIGHT}_MIN_THREE_PRIME_DISTANCE specified
  
  TASK_OPTIONS = %w(generic check_primers pick_primer_list pick_sequencing_primers pick_cloning_primers pick_discriminative_primers)
  MISPRIMING_LIBRARY_OPTIONS = %w(NONE HUMAN RODENT_AND_SIMPLE RODENT DROSOPHILA)
  PRIMER_TM_FORMULA_OPTIONS = ["Breslauer et al. 1986", "SantaLucia 1998"]
  SALT_CORRECTION_OPTIONS = ["Schildkraut and Lifson 1965","SantaLucia 1998","Owczarzy et. 2004"]
  
  
		attr_accessible :p3_file_type,
		:p3_file_id,
		:p3_file_flag,
		:p3_comment,
		:sequence_excluded_region,
		:sequence_force_left_end,
		:sequence_force_left_start,
		:sequence_force_right_end,
		:sequence_force_right_start,
		:sequence_id,
		:sequence_included_region,
		:sequence_internal_excluded_region,
		:sequence_internal_oligo,
		:sequence_overlap_junction_list,
		:sequence_primer,
		:sequence_primer_pair_ok_region_list,
		:sequence_primer_revcomp,
		:sequence_quality,
		:sequence_start_codon_position,
		:sequence_target,
		:sequence_template,
		:primer_dna_conc,
		:primer_dntp_conc,
		:primer_explain_flag,
		:primer_first_base_index,
		:primer_gc_clamp,
		:primer_inside_penalty,
		:primer_internal_dna_conc,
		:primer_internal_dntp_conc,
		:primer_internal_max_gc,
		:primer_internal_max_hairpin_th,
		:primer_internal_max_library_mishyb,
		:primer_internal_max_ns_accepted,
		:primer_internal_max_poly_x,
		:primer_internal_max_self_any,
		:primer_internal_max_self_any_th,
		:primer_internal_max_self_end,
		:primer_internal_max_self_end_th,
		:primer_internal_max_size,
		:primer_internal_max_tm,
		:primer_internal_min_gc,
		:primer_internal_min_quality,
		:primer_internal_min_size,
		:primer_internal_min_tm,
		:primer_internal_mishyb_library,
		:primer_internal_opt_gc_percent,
		:primer_internal_opt_size,
		:primer_internal_opt_tm,
		:primer_internal_salt_divalent,
		:primer_internal_salt_monovalent,
		:primer_internal_wt_end_qual,
		:primer_internal_wt_gc_percent_gt,
		:primer_internal_wt_gc_percent_lt,
		:primer_internal_wt_hairpin_th,
		:primer_internal_wt_library_mishyb,
		:primer_internal_wt_num_ns,
		:primer_internal_wt_self_any,
		:primer_internal_wt_self_any_th,
		:primer_internal_wt_self_end,
		:primer_internal_wt_self_end_th,
		:primer_internal_wt_seq_qual,
		:primer_internal_wt_size_gt,
		:primer_internal_wt_size_lt,
		:primer_internal_wt_tm_gt,
		:primer_internal_wt_tm_lt,
		:primer_liberal_base,
		:primer_lib_ambiguity_codes_consensus,
		:primer_lowercase_masking,
		:primer_max_end_gc,
		:primer_max_end_stability,
		:primer_max_gc,
		:primer_max_hairpin_th,
		:primer_max_library_mispriming,
		:primer_max_ns_accepted,
		:primer_max_poly_x,
		:primer_max_self_any,
		:primer_max_self_any_th,
		:primer_max_self_end,
		:primer_max_self_end_th,
		:primer_max_size,
		:primer_max_template_mispriming,
		:primer_max_template_mispriming_th,
		:primer_max_tm,
		:primer_min_3_prime_overlap_of_junction,
		:primer_min_5_prime_overlap_of_junction,
		:primer_min_end_quality,
		:primer_min_gc,
		:primer_min_left_three_prime_distance,
		:primer_min_quality,
		:primer_min_right_three_prime_distance,
		:primer_min_size,
		#:primer_min_three_prime_distance,
		:primer_min_tm,
		:primer_mispriming_library,
		:primer_num_return,
		:primer_opt_gc_percent,
		:primer_opt_size,
		:primer_opt_tm,
		:primer_outside_penalty,
		:primer_pair_max_compl_any,
		:primer_pair_max_compl_any_th,
		:primer_pair_max_compl_end,
		:primer_pair_max_compl_end_th,
		:primer_pair_max_diff_tm,
		:primer_pair_max_library_mispriming,
		:primer_pair_max_template_mispriming,
		:primer_pair_max_template_mispriming_th,
		:primer_pair_wt_compl_any,
		:primer_pair_wt_compl_any_th,
		:primer_pair_wt_compl_end,
		:primer_pair_wt_compl_end_th,
		:primer_pair_wt_diff_tm,
		:primer_pair_wt_io_penalty,
		:primer_pair_wt_library_mispriming,
		:primer_pair_wt_product_size_gt,
		:primer_pair_wt_product_size_lt,
		:primer_pair_wt_product_tm_gt,
		:primer_pair_wt_product_tm_lt,
		:primer_pair_wt_pr_penalty,
		:primer_pair_wt_template_mispriming,
		:primer_pair_wt_template_mispriming_th,
		:primer_pick_anyway,
		:primer_pick_internal_oligo,
		:primer_pick_left_primer,
		:primer_pick_right_primer,
		:primer_product_max_tm,
		:primer_product_min_tm,
		:primer_product_opt_size,
		:primer_product_opt_tm,
		:primer_product_size_range,
		:primer_quality_range_max,
		:primer_quality_range_min,
		:primer_salt_corrections,
		:primer_salt_divalent,
		:primer_salt_monovalent,
		:primer_sequencing_accuracy,
		:primer_sequencing_interval,
		:primer_sequencing_lead,
		:primer_sequencing_spacing,
		:primer_task,
		:primer_thermodynamic_oligo_alignment,
		:primer_thermodynamic_parameters_path,
		:primer_thermodynamic_template_alignment,
		:primer_tm_formula,
		:primer_wt_end_qual,
		:primer_wt_end_stability,
		:primer_wt_gc_percent_gt,
		:primer_wt_gc_percent_lt,
		:primer_wt_hairpin_th,
		:primer_wt_library_mispriming,
		:primer_wt_num_ns,
		:primer_wt_pos_penalty,
		:primer_wt_self_any,
		:primer_wt_self_any_th,
		:primer_wt_self_end,
		:primer_wt_self_end_th,
		:primer_wt_seq_qual,
		:primer_wt_size_gt,
		:primer_wt_size_lt,
		:primer_wt_template_mispriming,
		:primer_wt_template_mispriming_th,
		:primer_wt_tm_gt,
		:primer_wt_tm_lt
    
    def defaults
      { :p3_file_type => 'settings',
      #:p3_file_flag => false,
      :p3_file_flag => 1,
      :sequence_force_left_end => -1_000_000,
      :sequence_force_left_start => -1_000_000,
      :sequence_force_right_end => -1_000_000,
      :sequence_force_right_start => -1_000_000,
      # :sequence_included_region
      # :sequence_internal_excluded_region => list,
      # :sequence_internal_oligo => sequence,
      # :sequence_overlap_junction_list => separated,
      # :sequence_primer => sequence,
      # :sequence_primer_pair_ok_region_list => separated,
      # :sequence_primer_revcomp => sequence,
      # :sequence_quality => separated,
      :sequence_start_codon_position => -2_000_000,
      # :sequence_target => list,
      # :sequence_template => sequence,
      :primer_dna_conc => 50.0,
      :primer_dntp_conc => 0.6,
      :primer_explain_flag => 0,
      :primer_first_base_index => 0,
      :primer_gc_clamp => 0,
      :primer_inside_penalty => -1.0,
      :primer_internal_dna_conc => 50.0,
      :primer_internal_dntp_conc => 0.0,
      :primer_internal_max_gc => 80.0,
      :primer_internal_max_hairpin_th => 47.0,
      :primer_internal_max_library_mishyb => 12.00,
      :primer_internal_max_ns_accepted => 0,
      :primer_internal_max_poly_x => 5,
      :primer_internal_max_self_any => 12.00,
      :primer_internal_max_self_any_th => 47.00,
      :primer_internal_max_self_end => 12.00,
      :primer_internal_max_self_end_th => 47.00,
      :primer_internal_max_size => 27,
      :primer_internal_max_tm => 63.0,
      :primer_internal_min_gc => 20.0,
      :primer_internal_min_quality => 0,
      :primer_internal_min_size => 18,
      :primer_internal_min_tm => 57.0,
      #:primer_internal_mishyb_library => ,
      :primer_internal_opt_gc_percent => 50.0,
      :primer_internal_opt_size => 20,
      :primer_internal_opt_tm => 60.0,
      :primer_internal_salt_divalent => 0.0,
      :primer_internal_salt_monovalent => 50.0,
      :primer_internal_wt_end_qual => 0.0,
      :primer_internal_wt_gc_percent_gt => 0.0,
      :primer_internal_wt_gc_percent_lt => 0.0,
      :primer_internal_wt_hairpin_th => 0.0,
      :primer_internal_wt_library_mishyb => 0.0,
      :primer_internal_wt_num_ns => 0.0,
      :primer_internal_wt_self_any => 0.0,
      :primer_internal_wt_self_any_th => 0.0,
      :primer_internal_wt_self_end => 0.0,
      :primer_internal_wt_self_end_th => 0.0,
      :primer_internal_wt_seq_qual => 0.0,
      :primer_internal_wt_size_gt => 1.0,
      :primer_internal_wt_size_lt => 1.0,
      :primer_internal_wt_tm_gt => 1.0,
      :primer_internal_wt_tm_lt => 1.0,
      :primer_liberal_base => 0,
      :primer_lib_ambiguity_codes_consensus => 0,
      :primer_lowercase_masking => 0,
      :primer_max_end_gc => 5,
      :primer_max_end_stability => 100.00,
      :primer_max_gc => 80.0,
      :primer_max_hairpin_th => 47.0,
      :primer_max_library_mispriming => 12.00,
      :primer_max_ns_accepted => 0,
      :primer_max_poly_x => 5,
      :primer_max_self_any => 8.00,
      :primer_max_self_any_th => 47.00,
      :primer_max_self_end => 3.00,
      :primer_max_self_end_th => 47.00,
      :primer_max_size => 27,
      :primer_max_template_mispriming => -1,
      :primer_max_template_mispriming_th => -1,
      :primer_max_tm => 63.0,
      :primer_min_3_prime_overlap_of_junction => 4,
      :primer_min_5_prime_overlap_of_junction => 7,
      :primer_min_end_quality => 0,
      :primer_min_gc => 20.0,
      :primer_min_left_three_prime_distance => -1,
      :primer_min_quality => 0,
      :primer_min_right_three_prime_distance => -1,
      :primer_min_size => 18,
      #:primer_min_three_prime_distance => -1,
      :primer_min_tm => 57.0,
      #:primer_mispriming_library => ,
      :primer_num_return => 5,
      :primer_opt_gc_percent => 50.0,
      :primer_opt_size => 20,
      :primer_opt_tm => 60.0,
      :primer_outside_penalty => 0.0,
      :primer_pair_max_compl_any => 8.00,
      :primer_pair_max_compl_any_th => 47.00,
      :primer_pair_max_compl_end => 3.00,
      :primer_pair_max_compl_end_th => 47.00,
      :primer_pair_max_diff_tm => 100.0,
      :primer_pair_max_library_mispriming => 24.00,
      :primer_pair_max_template_mispriming => -1.00,
      :primer_pair_max_template_mispriming_th => -1.00,
      :primer_pair_wt_compl_any => 0.0,
      :primer_pair_wt_compl_any_th => 0.0,
      :primer_pair_wt_compl_end => 0.0,
      :primer_pair_wt_compl_end_th => 0.0,
      :primer_pair_wt_diff_tm => 0.0,
      :primer_pair_wt_io_penalty => 0.0,
      :primer_pair_wt_library_mispriming => 0.0,
      :primer_pair_wt_product_size_gt => 0.0,
      :primer_pair_wt_product_size_lt => 0.0,
      :primer_pair_wt_product_tm_gt => 0.0,
      :primer_pair_wt_product_tm_lt => 0.0,
      :primer_pair_wt_pr_penalty => 1.0,
      :primer_pair_wt_template_mispriming => 0.0,
      :primer_pair_wt_template_mispriming_th => 0.0,
      :primer_pick_anyway => 0,
      :primer_pick_internal_oligo => 0,
      :primer_pick_left_primer => 1,
      :primer_pick_right_primer => 1,
      :primer_product_max_tm => 1000000.0,
      :primer_product_min_tm => -1000000.0,
      :primer_product_opt_size => 0,
      :primer_product_opt_tm => 0.0,
      #:primer_product_size_range => range,
      :primer_quality_range_max => 100,
      :primer_quality_range_min => 0,
      :primer_salt_corrections => 1,
      :primer_salt_divalent => 1.5,
      :primer_salt_monovalent => 50.0,
      :primer_sequencing_accuracy => 20,
      :primer_sequencing_interval => 250,
      :primer_sequencing_lead => 50,
      :primer_sequencing_spacing => 500,
      :primer_task => 'generic',
      :primer_thermodynamic_oligo_alignment => 1,
      :primer_thermodynamic_parameters_path => './primer3_config',
      :primer_thermodynamic_template_alignment => 0,
      :primer_tm_formula => 1,
      :primer_wt_end_qual => 0.0,
      :primer_wt_end_stability => 0.0,
      :primer_wt_gc_percent_gt => 0.0,
      :primer_wt_gc_percent_lt => 0.0,
      :primer_wt_hairpin_th => 0.0,
      :primer_wt_library_mispriming => 0.0,
      :primer_wt_num_ns => 0.0,
      :primer_wt_pos_penalty => 1.0,
      :primer_wt_self_any => 0.0,
      :primer_wt_self_any_th => 0.0,
      :primer_wt_self_end => 0.0,
      :primer_wt_self_end_th => 0.0,
      :primer_wt_seq_qual => 0.0,
      :primer_wt_size_gt => 1.0,
      :primer_wt_size_lt => 1.0,
      :primer_wt_template_mispriming => 0.0,
      :primer_wt_template_mispriming_th => 0.0,
      :primer_wt_tm_gt => 1.0,
      :primer_wt_tm_lt => 1.0 }
    end
end
